<?php

namespace MusicShop\FrontendBundle\Repository;

/**
 * ArtistsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistsRepository extends \Doctrine\ORM\EntityRepository
{
}
